# Generated by Django 5.1.6 on 2025-03-02 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0002_person_gender_person_phone_number_person_ypt_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('camp_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camps_directed', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geo_location', models.JSONField()),
                ('assistant_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_assistant_directed', to='person.person')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_directed', to='person.person')),
                ('staff', models.ManyToManyField(blank=True, related_name='areas_staff', to='person.person')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='camp.camp')),
            ],
        ),
    ]
